### ISSUE TITLE
I don't see any data in screen, unless I resize the window

### ISSUE THREAD

**Issue by sanderheijselaar** [Nenkai/PDTools#3]
![SimulatorInterface](https://user-images.githubusercontent.com/2115388/180857107-22f70f32-adcd-4086-885b-03e8b70a9a26.gif)

Looks like it clear the screen right after printing everything.

**Comment by Nenkai** [comment]
I have a feeling this may be due to the regular console being too slow. Could you try with the Windows Terminal as a temporary fix?

**Comment by sanderheijselaar** [comment]
I've downloaded Windows Terminal in the MS Store and it works. Thanks for the tip (and the great work)
