### ISSUE TITLE
Throttle\brake to Int\Percentage?

### ISSUE THREAD

**Issue by Thomaswalbeck** [Nenkai/PDTools#5]
https://github.com/Nenkai/PDTools/blob/4749436b5f6aad2c989fa538bb4808f17ef0d7c9/SimulatorInterface/SimulatorPacketGT7.cs#L214

I saw the video you posted on twitter, and was just curious why you chose Bytes and not Int\Percentage? Since 255 is 100% throttle\brake, might be some more calculations to be done?

**Comment by Nenkai** [comment]
The game sends it as a byte. I tried not to alter any data sent (at the exception of some time based fields).
