### ISSUE TITLE
Possible new data groups

### ISSUE THREAD

**Issue by Jopo-JP** [Nenkai/PDTools#6]
I tested it a bit.

0x54 = seems to be related to the current power of a car. If you shift, the value gets lower. If you reach the RPM limit, it at the highest it can get on the car. 
On slower cars 6.20 seems to be max and like tomohawk will reach 7.01.
The old LMP porsche has a idle rate of 5.00 while most street cars have 1.60.
Maybe a modifier? i don't think it is torque.

0x94 and 0xC4 = seems to be suspension related. While in air, these value also will freeze

0x2C = is most likely a G meter. Like the red dot over the acceleration bar, which is going left and right. So the game telle a expensive rig how much G in which direction is happening, so it will move accordingly?

**Comment by Nenkai** [comment]
For 0x2C, i don't think it's g-force related. Comparing a regular car to the tomahawk lays similar values, but it seems like some sort of artificial force on the car.
The third value can go higher whenever the car lifts.

For 0x54, i first thought that it could be torque related, but i ain't too sure.
