### ISSUE TITLE
GTPatcher

### ISSUE THREAD

**Issue by Sulacoman** [Nenkai/PDTools#8]
Is expected support for the CUSA24769 release coming to GTpatcher? Thx

**Comment by Nenkai** [comment]
Wasn't planned in the first place.

**Comment by Sulacoman** [comment]
Since CUSA24769 is primarily available on a JB console, it's a rather limited group who can test it. Nevertheless, I greatly appreciate your work. It's truly impressive.

**Comment by Nenkai** [comment]
Using my tools on pirated copies are and will never be the intent

**Comment by Sulacoman** [comment]
I'm a bit confused because this is a JB console patcher... but I understand the main point. Thank you for the response.
